name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: set lower case owner name
        env:
          GH_ACTOR:  ${{github.actor}}
        run: echo "GH_USER=${GH_ACTOR,,}" >>${GITHUB_ENV}

      - name: 'Build Docker Image'
        env:
          IMG_VERSION: ${{ github.ref_name }}
          # GH_USER: ${{github.actor}}
        run: docker build . --tag ghcr.io/"$GH_USER"/latex-img:"$IMG_VERSION"

      - name: 'Push Docker Image'
        env:
          IMG_VERSION: ${{ github.ref_name }}
          # GH_USER: ${{github.actor}}
        run: docker push ghcr.io/"$GH_USER"/latex-img:"$IMG_VERSION"
