name: Build and deploy Images to ghcr.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'Set GH_USER to lower case github.actor'
        env:
          GH_ACTOR: ${{ github.actor }}
        run: echo "GH_USER=${GH_ACTOR,,}" >>${GITHUB_ENV}

      - name: 'Login to ghcr.io'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build Docker Image'
        env:
          IMG_VERSION: ${{ github.ref_name }}
        run: docker build . --tag ghcr.io/"$GH_USER"/latex-img:"$IMG_VERSION"

      - name: 'Push Docker Image'
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          IMG_VERSION: ${{ github.ref_name }}
        run: docker push ghcr.io/"$GH_USER"/latex-img:"$IMG_VERSION"
